name: 3d_tracking_ik
channels:
  - conda-forge
dependencies:
  - python=3.13
  - uv
  - ffmpeg
  - glew
  - mesalib
  - glfw
  - matplotlib
  - cuda-version>=12.2,<=12.9
variables:            # MuJoCo needs EGL for headless rendering on GPU nodes
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
